version: '2.1'
services:
    chrome_api:
        restart: always
        build: .
        container_name: chrome_api
        networks:
            - proxy
        ports:
            - 4300:4300
        volumes:
            - .:/usr/src/app

    worker:
        restart: always
        build: .
        command: bash -c "node client.js"
        container_name: chrome_api_worker
        networks:
            - proxy
        volumes:
            - .:/usr/src/app


networks:
    proxy:
        name: proxy
